[system]
name = 'misc/bmrcd.pdb'
output = 'test.pdb'

[minimize]
vacuum = true
implicit_solvent = true

[lipids]
[lipids.0]
resid = 5
restype = 'POPC'
current_resname = 'POV'

[lipids.1]
resid = 9
restype = 'POPA'
current_resname = 'POV'
