name: cryo
channels:
  - defaults
  - conda-forge
dependencies:
  - appdirs=1.4.4
  - biopython=1.80
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.10.11
  - cached-property=1.5.2
  - certifi=2020.6.20
  - cffi=1.15.1
  - cftime=1.6.2
  - charset-normalizer=2.0.4
  - contourpy=1.0.6
  - cryptography=39.0.0
  - curl=7.87.0
  - cycler=0.11.0
  - fasteners=0.16.3
  - fonttools=4.25.0
  - freetype=2.12.1
  - griddataformats=1.0.1
  - gsd=2.7.0
  - h5py=3.7.0
  - hdf4=4.2.15
  - hdf5=1.12.2
  - idna=3.3
  - joblib=1.1.0
  - jpeg=9e
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.12
  - lerc=4.0.0
  - libaec=1.0.6
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcurl=7.87.0
  - libcxx=14.0.6
  - libdeflate=1.14
  - libedit=3.1.20221030
  - libev=4.33
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - liblapack=3.9.0
  - libnetcdf=4.8.1
  - libnghttp2=1.51.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libsqlite=3.40.0
  - libssh2=1.10.0
  - libtiff=4.4.0
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libzip=1.9.2
  - libzlib=1.2.13
  - llvm-openmp=14.0.6
  - matplotlib=3.6.2
  - matplotlib-base=3.6.2
  - mdanalysis=2.4.2
  - mmtf-python=1.1.3
  - mrcfile=1.4.3
  - msgpack-python=1.0.4
  - munkres=1.1.4
  - ncurses=6.3
  - netcdf4=1.6.2
  - networkx=2.7.1
  - numpy=1.24.1
  - openjpeg=2.5.0
  - openssl=3.0.7
  - packaging=21.3
  - pandas=1.5.2
  - pbr=5.6.0
  - pillow=9.2.0
  - pip=22.3.1
  - pooch=1.4.0
  - pthread-stubs=0.3
  - pycparser=2.21
  - pyedr=0.7.1
  - pyopenssl=22.0.0
  - pyparsing=3.0.4
  - pysocks=1.7.1
  - python=3.11.0
  - python-dateutil=2.8.2
  - python_abi=3.11
  - pytng=0.3.0
  - pytz=2021.3
  - readline=8.1.2
  - requests=2.27.1
  - scikit-learn=1.1.3
  - scipy=1.10.0
  - seaborn=0.11.2
  - setuptools=65.6.3
  - six=1.16.0
  - threadpoolctl=2.2.0
  - tidynamics=1.0.0
  - tk=8.6.12
  - tornado=6.2
  - tqdm=4.49.0
  - tzdata=2022g
  - urllib3=1.26.8
  - wheel=0.38.4
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - zstd=1.5.2
  - pip:
      - cython==0.29.33
      - deprecated==1.2.13
      - hopcroftkarp==1.2.5
      - jinja2==3.1.2
      - kmapper==2.0.1
      - markupsafe==2.1.1
      - persim==0.3.1
      - ripser==0.6.4
      - scikit-tda==1.0.0
      - tadasets==0.0.4
      - wrapt==1.14.1
